Shop.WebUI/Controllers/BasketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Shop.Services;

namespace Shop.WebUI.Controllers
{
    public class BasketsController : Controller
    {
        private IBasketService _basketService;

        public BasketsController(IBasketService basketService)
        {
            this._basketService = basketService;
        }

        // GET: Baskets
        public ActionResult Index()
        {
            var model = _basketService.GetBasketItems(this.HttpContext);
            return View(model);
        }

        public ActionResult AddToBasket(string Id)
        {
            _basketService.AddToBasket(this.HttpContext, Id);
            return RedirectToAction("Index");
        }

        public ActionResult RemoveFromBasket(string Id)
        {
            _basketService.RemoveFromBasket(this.HttpContext, Id);
            return RedirectToAction("Index");
        }

        public PartialViewResult BasketSummary()
        {
            var basketSummary = _basketService.GetBasketSummary(this.HttpContext);
            return PartialView(basketSummary);
        }
    }
}

Shop.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Core.Contracts;
using Core.Models;
using Core.ViewModels;

namespace Shop.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private IBaseRepository<Product> product;
        private IBaseRepository<ProductCategory> productCategories;

        public HomeController(IBaseRepository<Product> productContext, IBaseRepository<ProductCategory> productCategoryContext)
        {
            product = productContext;
            productCategories = productCategoryContext;
        }

        public ActionResult Index(string Category = null)
        {
            List<Product> products;
            List<ProductCategory> productCategory = productCategories.Collection().ToList();
            if (Category == null)
            {
                products = product.Collection().ToList();
            }
            else
            {
                products = product.Collection().Where(p => p.Category == Category).ToList();
            }
            ProductListViewModel model = new ProductListViewModel();
            model.Products = products;
            model.ProductCategories = productCategory;
            return View(model);
        }

        public ActionResult Details(string Id)
        {
            Product prd = product.Find(Id);
            if (prd == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(prd);
            }
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Shop.WebUI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Shop.WebUI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Shop.WebUI/Views/Home/Details.cshtml
@model Core.Models.Product

@{
    ViewBag.Title = Model.Name + "Details";
}

<h2>@Html.DisplayFor(model => model.Name)</h2>
<div>
    <div class="col-md-2">
        <img src="~/Content/ProductImages/@Model.Image" class="img-responsive"  />
    </div>
    <div class="col-md-10">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CreatedAt)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price) VND
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Category)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Category)
            </dd>

            <dt></dt>
            <a href="@Url.Action("AddToBasket","Baskets", new {Id = Model.Id})" class="btn btn-success">Add to basket</a>
            <dt></dt>
            @Html.ActionLink("Back to List", "Index")
            <dd></dd>
        </dl>
    </div>
</div>
<div class="col-md-12 clearfix"></div>

Shop.WebUI/Views/Home/Index.cshtml
@model Core.ViewModels.ProductListViewModel
@{
    ViewBag.Title = "Home Page";
}

<h1>Product</h1>

<div class="col-md-2">
    <h4>Filter by category</h4>
    <div class="list-group">
        @Html.ActionLink("All  ", "Index", null, new { @class = Request["Category"] == null ? "list-group-item active" : "list-group-item" })
        @foreach (var cat in Model.ProductCategories)
        {
            @Html.ActionLink(cat.Category + " ", "Index", new { Category = cat.Category }, new { @class = Request["Category"] == cat.Category? "list-group-item active" : "list-group-item" })
        }
    </div>
</div>
<div class="col-md-10">
    @foreach (var item in Model.Products)
    {
        <div class="col-md-4" style="height: 450px; padding: 10px; margin: 10px; border: 1px solid whitesmoke">
            <div class="col-md-12">
                <img class="img-responsive" style="height:250px" src="~/Content/ProductImages/@item.Image" />
            </div>
            <div class="col-md-12">
                <strong>@Html.ActionLink(item.Name, "Details", new { id = item.Id })</strong>
            </div>
            <div class="col-md-12">
                <p>@item.Description</p>
            </div>
            <div class="col-md-12">
                <p>@item.Price</p>
            </div>
            <div class="col-md-12">
                <a href="@Url.Action("AddToBasket","Baskets", new {Id = item.Id})" class="btn btn-success">Add to basket</a>
            </div>
        </div>
    }
</div>
<div class="col-md-12 clearfix"></div>